### ISSUE TITLE
exception if there is no DTEND

### ISSUE THREAD

**Issue by huckley** [albertyw/csv-ical#19]
I have a ics files with some recurring elements which have no DTEND, so it throws a exception:
`
Traceback (most recent call last):
  File "./convert", line 8, in <module>
    convert.make_csv()
  File "/usr/local/lib/python3.7/dist-packages/csv_ical/convert.py", line 78, in make_csv
    event.get('DTEND').dt,
AttributeError: 'NoneType' object has no attribute 'dt'
`

**Comment by albertyw** [comment]
Fixed in a2153f2
